---
title: "final-project"
author: "Murphy John"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(stringr)
library(psych)
library(gmodels)
library(survival)
library(survminer)
```


```{r}
# load data
seer <- readRDS("data/processed/seer.rds")
attach(seer)
```


```{r}
# Table 1: Clinicopathological Characteristics by Breast Cancer Subtype
# (unadjusted associations between covariates and exposure)

## agecat
CrossTable(agecat, subtype, prop.r = FALSE, prop.c = TRUE, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE)

## race
CrossTable(racecat, subtype, prop.r = FALSE, prop.c = TRUE, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE)

## marriage status
CrossTable(marriage_status, subtype, prop.r = FALSE, prop.c = TRUE, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE)

## N stage
CrossTable(n_stage, subtype, prop.r = FALSE, prop.c = TRUE, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE)

## M stage
CrossTable(m_stage, subtype, prop.r = FALSE, prop.c = TRUE, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE)

## grade
CrossTable(grade, subtype, prop.r = FALSE, prop.c = TRUE, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE, useNA = "always")

## radiation
CrossTable(radiation, subtype, prop.r = FALSE, prop.c = TRUE, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE)

## chemotherapy
CrossTable(chemotherapy, subtype, prop.r = FALSE, prop.c = TRUE, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE)

## surgery
CrossTable(surgery, subtype, prop.r = FALSE, prop.c = TRUE, prop.t = FALSE, prop.chisq = FALSE, chisq = TRUE)
```

```{r}
# Table 2: Clinicopathological Characteristics by survival
# (Unadjusted associations between covariates and survival) also median survival

## agecat
survfit(Surv(survival_months, survival_status)~agecat)
summary(survfit(Surv(time = survival_months, event = survival_status) ~ agecat), times = c(12, 60, 120))
survdiff(Surv(time = survival_months, event = survival_status) ~ agecat)

## race
survfit(Surv(survival_months, survival_status)~racecat)
summary(survfit(Surv(time = survival_months, event = survival_status) ~ racecat), times = c(12, 60, 120))
survdiff(Surv(time = survival_months, event = survival_status) ~ racecat)

## marriage status
survfit(Surv(survival_months, survival_status)~marriage_status)
summary(survfit(Surv(time = survival_months, event = survival_status) ~ marriage_status), times = c(12, 60, 120))
survdiff(Surv(time = survival_months, event = survival_status) ~ marriage_status)

## N stage
survfit(Surv(survival_months, survival_status)~n_stage)
summary(survfit(Surv(time = survival_months, event = survival_status) ~ n_stage), times = c(12, 60, 120))
survdiff(Surv(time = survival_months, event = survival_status) ~ n_stage)

## M stage
survfit(Surv(survival_months, survival_status)~m_stage)
summary(survfit(Surv(time = survival_months, event = survival_status) ~ m_stage), times = c(12, 60, 120))
survdiff(Surv(time = survival_months, event = survival_status) ~ m_stage)

## grade
survfit(Surv(survival_months, survival_status)~grade)
summary(survfit(Surv(time = survival_months, event = survival_status) ~ grade), times = c(12, 60, 120))
survdiff(Surv(time = survival_months, event = survival_status) ~ grade)

## radiation
survfit(Surv(survival_months, survival_status)~radiation)
summary(survfit(Surv(time = survival_months, event = survival_status) ~ radiation), times = c(12, 60, 120))
survdiff(Surv(time = survival_months, event = survival_status) ~ radiation)

## chemotherapy
survfit(Surv(survival_months, survival_status)~chemotherapy)
summary(survfit(Surv(time = survival_months, event = survival_status) ~ chemotherapy), times = c(12, 60, 120))
survdiff(Surv(time = survival_months, event = survival_status) ~ chemotherapy)

## surgery
survfit(Surv(survival_months, survival_status)~surgery)
summary(survfit(Surv(time = survival_months, event = survival_status) ~ surgery), times = c(12, 60, 120))
survdiff(Surv(time = survival_months, event = survival_status) ~ surgery)
```

```{r}
# Figure 2: Log-log plots to check Proportional Hazards assumption
library(gridExtra)
library(survminer)
library(survival)

plot_subtype <- ggsurvplot(
  survfit(Surv(time = survival_months, event = survival_status) ~ subtype), 
  data = seer, 
  fun ="cloglog",
  ylab = "Log-log survival probability",
  xlab = "Time (months)",
  legend.labs = c("Luminal A", "Luminal B", "HER2 Positive", "Triple Negative"))

plot_agecat <- ggsurvplot(
  survfit(Surv(time = survival_months, event = survival_status) ~ agecat), 
  data = seer, 
  fun="cloglog",
  ylab= "Log-log survival probability",
  xlab= "Time (months)",
  legend.labs = c("20-49 years", "50-69 years", ">= 70 years"))

plot_race <- ggsurvplot(
  survfit(Surv(time = survival_months, event = survival_status) ~ racecat), 
  data = seer, 
  fun="cloglog",
  ylab= "Log-log survival probability",
  xlab= "Time (months)",
  legend.labs = c("White", "Black", "Other"))

plot_marriage <- ggsurvplot(
  survfit(Surv(time = survival_months, event = survival_status) ~ marriage_status), 
  data = seer, 
  fun="cloglog",
  ylab= "Log-log survival probability",
  xlab= "Time (months)",
  legend.labs = c("Unmarried", "Married"))

plot_n_stage <- ggsurvplot(
  survfit(Surv(time = survival_months, event = survival_status) ~ n_stage), 
  data = seer, 
  fun="cloglog",
  ylab= "Log-log survival probability",
  xlab= "Time (months)",
  legend.labs = c("N0/1", "N2/3"))

plot_m_stage <- ggsurvplot(
  survfit(Surv(time = survival_months, event = survival_status) ~ m_stage), 
  data = seer, 
  fun="cloglog",
  ylab= "Log-log survival probability",
  xlab= "Time (months)",
  legend.labs = c("M0", "M1"))

plot_grade <- ggsurvplot(
  survfit(Surv(time = survival_months, event = survival_status) ~ grade), 
  data = seer, 
  fun="cloglog",
  ylab= "Log-log survival probability",
  xlab= "Time (months)",
  legend.labs = c("I/II", "III/IV"))

plot_radiation <- ggsurvplot(
  survfit(Surv(time = survival_months, event = survival_status) ~ radiation), 
  data = seer, 
  fun="cloglog",
  ylab= "Log-log survival probability",
  xlab= "Time (months)",
  legend.labs = c("No/Unknown", "Yes"))

plot_chemotherapy <- ggsurvplot(
  survfit(Surv(time = survival_months, event = survival_status) ~ chemotherapy), 
  data = seer, 
  fun="cloglog",
  ylab= "Log-log survival probability",
  xlab= "Time (months)",
  legend.labs = c("No/Unknown", "Yes"))


plot_surgery <- ggsurvplot(
  survfit(Surv(time = survival_months, event = survival_status) ~ surgery), 
  data = seer, 
  fun="cloglog",
  ylab= "Log-log survival probability",
  xlab= "Time (months)",
  legend.labs = c("No/Unknown", "Yes"))

grid.arrange(plot_subtype$plot, plot_agecat$plot, plot_race$plot, plot_marriage$plot, plot_n_stage$plot,
             plot_m_stage$plot, plot_grade$plot, plot_radiation$plot, plot_chemotherapy$plot, plot_surgery$plot,
             ncol = 5, nrow = 2)
```



```{r}
# check the proportional hazards assumption for each covariate with (1) a log log plot

## subtype
ggsurvplot(survfit(Surv(time = survival_months, event = survival_status) ~ subtype), data = seer, fun="cloglog")

## agecat
ggsurvplot(survfit(Surv(time = survival_months, event = survival_status) ~ agecat), data = seer, fun="cloglog")

## race
ggsurvplot(survfit(Surv(time = survival_months, event = survival_status) ~ racecat), data = seer, fun="cloglog")

## marriage status
ggsurvplot(survfit(Surv(time = survival_months, event = survival_status) ~ marriage_status), data = seer, fun="cloglog")

## N stage
ggsurvplot(survfit(Surv(time = survival_months, event = survival_status) ~ n_stage), data = seer, fun="cloglog")

## M stage
ggsurvplot(survfit(Surv(time = survival_months, event = survival_status) ~ m_stage), data = seer, fun="cloglog")

## grade
ggsurvplot(survfit(Surv(time = survival_months, event = survival_status) ~ grade), data = seer, fun="cloglog")

## radiation
ggsurvplot(survfit(Surv(time = survival_months, event = survival_status) ~ radiation), data = seer, fun="cloglog")

## chemotherapy
ggsurvplot(survfit(Surv(time = survival_months, event = survival_status) ~ chemotherapy), data = seer, fun="cloglog")

## surgery
ggsurvplot(survfit(Surv(time = survival_months, event = survival_status) ~ surgery), data = seer, fun="cloglog")
```

```{r}
# create a dataset in counting process format
seer.cpfull <- survSplit(seer, cut=seer$survival_months[seer$survival_status==1],
                     end="survival_months",event="survival_status", start="start")
# remove NA because the model will do this anyways
seer.cp <- na.omit(seer.cpfull)
```

```{r}
model <- coxph(
  Surv(survival_months, survival_status) ~ 
    relevel(factor(subtype), ref = '0') +
    relevel(factor(agecat), ref = '0') + 
    relevel(factor(racecat), ref = '0') +
    relevel(factor(marriage_status),ref='1') + 
    relevel(factor(n_stage),ref='0') + 
    relevel(factor(m_stage),ref='0') +
    relevel(factor(grade), ref='0') +
    relevel(factor(radiation), ref='1') + 
    relevel(factor(chemotherapy), ref='1') +
    relevel(factor(surgery), ref='1'),
  data = seer, 
  method = "breslow")

summary(model)

# Test proportional hazards assumption with Schoenfeld residuals
resid <- cox.zph(model, terms = FALSE)

# get the correlations between residuals and ranked survival times
apply(resid$y, 2, \(x) cor.test(rank(resid$time), x))
# subtype1: -0.034
# subtype2: -0.1296
# subtype3: -0.0435
# agecat1: -0.0331
# agecat2: -0.0304
# racecat1: 0.0077
# racecat2: 0.0102
# marraige_status0: 0.0043
# n_stage1: 0.0188
# m_stage: -0.0046
# grade: -0.0412
# radiation: -0.072
# chemotherapy: -0.1122
# surgery: -0.0715

cor <- apply(resid$y, 2, \(x) {
  test <- cor.test(rank(resid$time), x)  # Perform correlation test
  c(
    correlation = test$estimate,
    p_value = test$p.value,
    conf_low = test$conf.int[1],
    conf_high = test$conf.int[2]
  ) 
})

cor_df <- as.data.frame(t(cor))
colnames(cor_df) <- c("Correlation", "P_Value", "Conf_Low", "Conf_High")
rownames(cor_df) <- c(
  "subtype1",
  "subtype2",
  "subtype3",
  "agecat1",
  "agecat2",
  "racecat1",
  "racecat2",
  "marraige_status0",
  "n_stage1",
  "m_stage",
  "grade",
  "radiation",
  "chemotherapy",
  "surgery"
)

```

```{r}
# fit extended model and see if interaction terms are significant
# create a dataset in counting process format
seer.cpfull <- survSplit(seer, cut=seer$survival_months[seer$survival_status==1],
                     end="survival_months",event="survival_status", start="start")
# remove NA because the model will do this anyways
seer.cp <- na.omit(seer.cpfull)

# create interaction between each subtype and log time
seer.cp$subtype1_time=seer.cp$subtype1*log(seer.cp$survival_months)
seer.cp$subtype2_time=seer.cp$subtype2*log(seer.cp$survival_months)
seer.cp$subtype3_time=seer.cp$subtype3*log(seer.cp$survival_months)

options(scipen=999)
model_ext <- coxph(
  formula = Surv(
    seer.cp$start, seer.cp$survival_months, seer.cp$survival_status) ~ 
    subtype1 + subtype2 + subtype3 + 
    relevel(factor(agecat), ref = '0') + 
    relevel(factor(racecat), ref = '0') +
    relevel(factor(marriage_status),ref='1') + 
    relevel(factor(n_stage),ref='0') + 
    relevel(factor(m_stage),ref='0') +
    relevel(factor(grade), ref='0') +
    relevel(factor(radiation), ref='1') + 
    relevel(factor(chemotherapy), ref='1') +
    relevel(factor(surgery), ref='1') +
    subtype1_time + subtype2_time + subtype3_time, 
  data = seer.cp, method="breslow")

summary(model_ext)

```










